name: E2E

on: [push]

jobs:
  e2e_testing:
    name: E2E Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm run start:test
          wait-on: 'http://localhost:3000'
